### ISSUE TITLE
temperature listed as 0 when negative

### ISSUE THREAD

**Issue by wormiedk** [DanTheMan827/homebridge-ds18b20#1]
hi there. The temperature reported is 0 whenever the temperature is below 0

**Comment by DanTheMan827** [comment]
Are you referring to below 0°C or 0°F?

**Comment by DanTheMan827** [comment]
And could you test it using the [npm package ds18b20](https://www.npmjs.com/package/ds18b20)?

**Comment by wormiedk** [comment]
Below 0°C 
As far as i know da18b20 always report in 0°C 

Cheers

**Comment by wormiedk** [comment]
The ds18b20 nodes package reports correctly Current temperature is -5.5

more /sys/bus/w1/devices/28-0000069621e9/w1_slave 
a8 ff 4b 46 7f ff 08 10 e5 : crc=e5 YES
a8 ff 4b 46 7f ff 08 10 e5 t=-5500

**Comment by Brightdawn** [comment]
after hours of debuggin i found the problem... the problem is, that in the HAP framwork, temperature sensors are defined with a range of 0-100 degrees
so. its not the sensors.. its not the ds18b20 library and its not the ds18b20 homebridge module.. they are all reporting negative numbers in the right way...

there are 2 possible fixes for this:
1. correct the 0-100 range in the HAP Framework by editing /usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/gen/HomeKitTypes.js
Go the Block: "Characteristic.CurrentTemperature" .. there you find
maxValue: 100,
minValue: 0,
minStep: 0.1,

just change minvalue to -50 or something
1. the developer of this ds18b20 module can override the setting by setting
   characteristic.props.minValue = -50
   I tried to do this, but I don't know where in the source i have to place this...

so .. i did Number 1 as a workaround and it works without any problem

see here: https://github.com/KhaosT/HAP-NodeJS/issues/147

**Comment by DanTheMan827** [comment]
Thanks for the info, I've fixed the issue and published the patch to npm
